# ? ?? master server? commit? ??? spring.config.import ???? ?? commit ??
spring:
  config:
    import: env.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_ADDRESS}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
          default_batch_fetch_size: 1000
  application:
    name: ${DOMAIN_NAME}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

aws.s3.bucketName: "stellagram-bucket-a101"
aws.s3.accessKey: ${ACCESS_KEY}
aws.s3.secretAccessKey: ${SECRET_ACCESS_KEY}